name: Build & deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**' # Only consider paths directly relevant to the build
      - 'README.md'

concurrency:
  group: "pages"
  cancel-in-progress: false

# NOTE: Make sure, in your environment secrets page, that "VITE_GOOGLE_KEY" is set!

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: build # Be sure to set your environment here that has "VITE_GOOGLE_KEY"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      - name: Clean install Node.js dependencies
        run: npm ci
      - name: Build package with Node.js
        run: npm run build # CI=false to ignore warnings
        env:
          CI: false
          VITE_GOOGLE_KEY: ${{ secrets.VITE_GOOGLE_KEY }}
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          name: build-artifact
          path: build/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5
        with:
          artifact_name: build-artifact
